# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 048d50431f977fe296977f06239c608c50e14d7fc3bf2af24892257742a9e64d03bb542377168aff2cc9373052a7bc730fde7f8bcf199d3023dc4340d9864e65

test:
  secret_key_base: 3d9a4499ee8247ab014753db25fe903f7cfe61bf801c2d5ca793370228788ff71e3c09e3e326d3952c68ed9933ea95753825110220a6cf3eacfd19f6f8615ce7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
